'use server';

import { createServerClient, createServiceClient } from '@/lib/supabase';
import { revalidatePath, unstable_cache } from 'next/cache';
import { cache } from 'react';
import { recordPointTransaction } from '@/app/actions/ledgerActions';

import { GROUP_TYPE_META } from '@/config/groupDefinitions';
export type { GroupTypeMeta } from '@/config/groupDefinitions';
import type { VillageMapTheme } from '@/config/villageMapThemes';
import { getVillageMapTheme } from '@/app/actions/mapActions';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GroupRow {
  id: string;
  name: string;
  type: string;
  min_members: number;
  max_members: number;
  pooled_points: number;
  theme_id: string;
  invite_code: string;
  created_at: string;
}

export interface GroupMemberRow {
  user_id: string;
  role: 'admin' | 'member';
  joined_at: string;
  display_name: string;
  avatar_url: string | null;
  points: number;
  /**
   * The member's active shell/habitat type (e.g. 'default_dollhouse', 'cozy_campsite', 'stone_castle').
   * Sourced from cozy.users.shell_type — column already exists (written by shellActions, read by profileActions).
   * No migration required. Note for sunshade-db-platform: preserve this column in any future users table alterations.
   */
  shell_type?: string;
  /**
   * The member's current emotional vibe status: 'sunshine' | 'neutral' | 'raincloud'.
   * Sourced from cozy.users.vibe_status.
   */
  vibe_status?: 'sunshine' | 'neutral' | 'raincloud';
}

export interface GroupWithMembers {
  group: GroupRow;
  members: GroupMemberRow[];
  currentUserRole: 'admin' | 'member' | null;
  memberCount: number;
  mapTheme?: VillageMapTheme;
}

export interface MyGroupEntry {
  group: GroupRow;
  role: 'admin' | 'member';
  memberCount: number;
}

export interface GroupActionResult {
  success: boolean;
  groupId?: string;
  error?: string;
}

// ---------------------------------------------------------------------------
// createGroup
//
// Creates a new group with the given name and type, then inserts the
// authenticated user as 'admin'. The invite_code is generated by the DB.
// ---------------------------------------------------------------------------

export async function createGroup(
  name: string,
  type: string
): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  // Validate type
  if (!GROUP_TYPE_META[type]) {
    return { success: false, error: `Invalid group type: ${type}` };
  }

  const meta = GROUP_TYPE_META[type];

  // Use service client for writes (RLS allows authenticated SELECT only)
  const service = createServiceClient();

  const { data: group, error: insertError } = await service
    .schema('cozy')
    .from('groups')
    .insert({
      name: name.trim(),
      type,
      max_members: meta.capacity,
      theme_id: meta.themeId,
    })
    .select('id')
    .single();

  if (insertError || !group) {
    console.error('[createGroup] Insert error:', insertError?.message);
    return { success: false, error: `Failed to create group: ${insertError?.message || 'Please try again.'}` };
  }

  // Add creator as admin
  const { error: memberError } = await service
    .schema('cozy')
    .from('group_members')
    .insert({ group_id: group.id, user_id: user.id, role: 'admin' });

  if (memberError) {
    console.error('[createGroup] Member insert error:', memberError.message);
    // Rollback the group — best effort
    await service.schema('cozy').from('groups').delete().eq('id', group.id);
    return { success: false, error: `Failed to add you to the group: ${memberError.message}` };
  }

  revalidatePath('/groups');
  return { success: true, groupId: group.id };
}

// ---------------------------------------------------------------------------
// joinGroup
//
// Validates group existence and capacity, then inserts the user as 'member'.
// Uses ON CONFLICT DO NOTHING so re-joining an existing group is a no-op.
// ---------------------------------------------------------------------------

export async function joinGroup(inviteCode: string): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  // Resolve group by invite code (public lookup — service bypasses RLS)
  const service = createServiceClient();

  const { data: group, error: fetchError } = await service
    .schema('cozy')
    .from('groups')
    .select('id, max_members')
    .eq('invite_code', inviteCode.trim().toLowerCase())
    .maybeSingle();

  if (fetchError) {
    console.error('[joinGroup] Fetch error:', fetchError.message);
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if (!group) {
    return { success: false, error: 'Invalid invite code. Double-check and try again.' };
  }

  // Check current member count against capacity
  const { count, error: countError } = await service
    .schema('cozy')
    .from('group_members')
    .select('*', { count: 'exact', head: true })
    .eq('group_id', group.id);

  if (countError) {
    console.error('[joinGroup] Count error:', countError.message);
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if ((count ?? 0) >= group.max_members) {
    return { success: false, error: 'This group is at full capacity. Ask the admin to upgrade the tier.' };
  }

  const { error: insertError } = await service
    .schema('cozy')
    .from('group_members')
    .upsert(
      { group_id: group.id, user_id: user.id, role: 'member' },
      { onConflict: 'group_id,user_id', ignoreDuplicates: true }
    );

  if (insertError) {
    console.error('[joinGroup] Insert error:', insertError.message);
    return { success: false, error: 'Failed to join group. Please try again.' };
  }

  revalidatePath('/groups');
  revalidatePath(`/groups/${group.id}`);
  return { success: true, groupId: group.id };
}

// ---------------------------------------------------------------------------
// upgradeGroupTier
//
// Validates that the caller is an admin and that the current member count
// meets requiredMinMembers before upgrading the group type and theme_id.
// ---------------------------------------------------------------------------

export async function upgradeGroupTier(
  groupId: string,
  newType: string,
  requiredMinMembers: number
): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  if (!GROUP_TYPE_META[newType]) {
    return { success: false, error: `Invalid group type: ${newType}` };
  }

  const service = createServiceClient();

  // Verify caller is admin
  const { data: membership, error: memberError } = await service
    .schema('cozy')
    .from('group_members')
    .select('role')
    .eq('group_id', groupId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (memberError || !membership || membership.role !== 'admin') {
    return { success: false, error: 'Only group admins can upgrade the tier.' };
  }

  // Check current member count
  const { count, error: countError } = await service
    .schema('cozy')
    .from('group_members')
    .select('*', { count: 'exact', head: true })
    .eq('group_id', groupId);

  if (countError) {
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if ((count ?? 0) < requiredMinMembers) {
    return {
      success: false,
      error: `You need at least ${requiredMinMembers} members to upgrade to ${GROUP_TYPE_META[newType].label}.`,
    };
  }

  const meta = GROUP_TYPE_META[newType];

  const { error: updateError } = await service
    .schema('cozy')
    .from('groups')
    .update({ type: newType, theme_id: meta.themeId, max_members: meta.capacity })
    .eq('id', groupId);

  if (updateError) {
    console.error('[upgradeGroupTier] Update error:', updateError.message);
    return { success: false, error: 'Failed to upgrade group. Please try again.' };
  }

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  return { success: true, groupId };
}

// ---------------------------------------------------------------------------
// contributeToGroup
//
// Transfers `points` from the authenticated user's personal balance into the
// group's pooled_points bank.
// ---------------------------------------------------------------------------

export interface ContributeResult {
  success: boolean;
  newPersonalPoints?: number;
  newPooledPoints?: number;
  error?: string;
}

export async function contributeToGroup(
  groupId: string,
  points: number
): Promise<ContributeResult> {
  if (points < 1 || !Number.isInteger(points)) {
    return { success: false, error: 'Contribution must be a positive whole number.' };
  }

  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  // 1. Invoke atomic database RPC transaction
  // Try cozy schema first, then fallback to public schema RPC alias
  let rpcData: any = null;
  let rpcError: any = null;

  const rpcPayload = {
    p_user_id: user.id,
    p_group_id: groupId,
    p_points: points,
  };

  try {
    const res = await supabase.schema('cozy').rpc('contribute_points', rpcPayload);
    rpcData = res.data;
    rpcError = res.error;
  } catch (err: any) {
    rpcError = err;
  }

  if (
    rpcError &&
    (rpcError.message?.includes('not found') ||
      rpcError.message?.includes('does not exist') ||
      rpcError.code === 'PGRST202')
  ) {
    try {
      const res = await supabase.rpc('contribute_points', rpcPayload);
      rpcData = res.data;
      rpcError = res.error;
    } catch (err: any) {
      rpcError = err;
    }
  }

  // 2. Handle domain errors & validation failures without executing non-atomic writes
  if (rpcError) {
    const msg = (rpcError.message || '').toLowerCase();
    if (msg.includes('insufficient points') || msg.includes('insufficient')) {
      return { success: false, error: "You don't have enough points for that contribution." };
    }
    if (msg.includes('not a member') || msg.includes('membership')) {
      return { success: false, error: 'You must be a group member to contribute.' };
    }
    if (msg.includes('group not found') || msg.includes('not found')) {
      return { success: false, error: 'Group not found.' };
    }
    if (msg.includes('positive')) {
      return { success: false, error: 'Contribution must be a positive whole number.' };
    }

    console.error('[contributeToGroup] RPC error:', rpcError.message || rpcError);
    return { success: false, error: rpcError.message || 'Something went wrong. Please try again.' };
  }

  // 3. Extract authoritative balances directly from the atomic transaction result
  const row = (Array.isArray(rpcData) ? rpcData[0] : rpcData) as {
    new_personal_points?: number;
    new_pooled_points?: number;
  };

  const newPersonalPoints = typeof row?.new_personal_points === 'number' ? row.new_personal_points : undefined;
  const newPooledPoints = typeof row?.new_pooled_points === 'number' ? row.new_pooled_points : undefined;

  // 4. Record group pool contribution in user's immutable transaction ledger
  await recordPointTransaction({
    userId: user.id,
    amount: -points,
    transactionType: 'group_contribution',
    description: `Contributed ${points} pts to group pool`,
  });

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  revalidatePath('/profile');

  return {
    success: true,
    newPersonalPoints,
    newPooledPoints,
  };
}

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// getMyGroups (server helper with multi-tier caching)
// ---------------------------------------------------------------------------

const getCachedUserGroups = unstable_cache(
  async (userId: string): Promise<MyGroupEntry[]> => {
    const service = createServiceClient();

    // 1. Fetch user's group memberships
    const { data: memberships, error: memberError } = await service
      .schema('cozy')
      .from('group_members')
      .select('group_id, role')
      .eq('user_id', userId);

    if (memberError || !memberships || memberships.length === 0) {
      if (memberError) console.error('[getMyGroups] Memberships query error:', memberError.message);
      return [];
    }

    const groupIds = memberships.map((m) => m.group_id);

    // 2. Fetch groups & member counts in parallel
    const [groupsRes, countsRes] = await Promise.all([
      service
        .schema('cozy')
        .from('groups')
        .select('id, name, type, min_members, max_members, pooled_points, theme_id, invite_code, created_at')
        .in('id', groupIds),
      service
        .schema('cozy')
        .from('group_members')
        .select('group_id')
        .in('group_id', groupIds),
    ]);

    if (groupsRes.error || !groupsRes.data) {
      console.error('[getMyGroups] Groups query error:', groupsRes.error?.message);
      return [];
    }

    const countMap: Record<string, number> = {};
    (countsRes.data ?? []).forEach((row: { group_id: string }) => {
      countMap[row.group_id] = (countMap[row.group_id] ?? 0) + 1;
    });

    const groupMap = new Map<string, GroupRow>();
    groupsRes.data.forEach((g) => groupMap.set(g.id, g as GroupRow));

    return memberships
      .map((m) => {
        const group = groupMap.get(m.group_id);
        if (!group) return null;
        return {
          group,
          role: m.role as 'admin' | 'member',
          memberCount: countMap[m.group_id] ?? 0,
        };
      })
      .filter((entry): entry is MyGroupEntry => entry !== null);
  },
  ['user-my-groups-cache'],
  {
    tags: ['groups'],
    revalidate: 60,
  }
);

export const getMyGroups = cache(async (): Promise<MyGroupEntry[]> => {
  const supabase = await createServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return [];

  return getCachedUserGroups(user.id);
});

// ---------------------------------------------------------------------------
// getGroupWithMembers (server helper with multi-tier caching)
// ---------------------------------------------------------------------------

interface RawGroupBundle {
  group: GroupRow;
  members: GroupMemberRow[];
  mapTheme?: VillageMapTheme;
}

const getCachedGroupData = unstable_cache(
  async (groupId: string): Promise<RawGroupBundle | null> => {
    const service = createServiceClient();

    // 1. Fetch group & members in parallel directly from DB
    const [groupRes, memberRes] = await Promise.all([
      service
        .schema('cozy')
        .from('groups')
        .select('id, name, type, min_members, max_members, pooled_points, theme_id, invite_code, created_at')
        .eq('id', groupId)
        .maybeSingle(),
      service
        .schema('cozy')
        .from('group_members')
        .select('user_id, role, joined_at')
        .eq('group_id', groupId),
    ]);

    if (groupRes.error || !groupRes.data) {
      if (groupRes.error) console.error('[getGroupWithMembers] Group fetch error:', groupRes.error.message);
      return null;
    }

    const group = groupRes.data as GroupRow;
    const memberships = memberRes.data ?? [];

    // Fetch dynamic map theme for group's theme_id and type
    const mapTheme = await getVillageMapTheme(group.theme_id, group.type);

    if (memberships.length === 0) {
      return { group, members: [], mapTheme };
    }

    // 2. Fetch user profiles for all member user_ids directly from cozy.users
    const userIds = memberships.map((m) => m.user_id);
    const { data: usersData, error: usersError } = await service
      .schema('cozy')
      .from('users')
      .select('id, display_name, avatar_url, points, shell_type, vibe_status')
      .in('id', userIds);

    if (usersError) {
      console.error('[getGroupWithMembers] Users query error:', usersError.message);
    }

    interface MemberUserRecord {
      id: string;
      display_name: string | null;
      avatar_url: string | null;
      points: number | null;
      shell_type: string | null;
      vibe_status: string | null;
    }

    const userMap = new Map<string, { display_name: string; avatar_url: string | null; points: number; shell_type?: string; vibe_status?: 'sunshine' | 'neutral' | 'raincloud' }>();
    ((usersData ?? []) as unknown as MemberUserRecord[]).forEach((u) => {
      userMap.set(u.id, {
        display_name: u.display_name || 'Cozy Neighbor',
        avatar_url: u.avatar_url || null,
        points: u.points ?? 0,
        shell_type: u.shell_type ?? undefined,
        vibe_status: (u.vibe_status as 'sunshine' | 'neutral' | 'raincloud') || 'neutral',
      });
    });

    const members: GroupMemberRow[] = memberships.map((m) => {
      const u = userMap.get(m.user_id);
      return {
        user_id: m.user_id,
        role: m.role as 'admin' | 'member',
        joined_at: m.joined_at,
        display_name: u?.display_name || 'Cozy Neighbor',
        avatar_url: u?.avatar_url || null,
        points: u?.points ?? 0,
        shell_type: u?.shell_type,
        vibe_status: u?.vibe_status || 'neutral',
      };
    });

    return {
      group,
      members,
      mapTheme,
    };
  },
  ['group-data-bundle-cache'],
  {
    tags: ['groups', 'village_map_themes'],
    revalidate: 30,
  }
);

export const getGroupWithMembers = cache(async (
  groupId: string
): Promise<GroupWithMembers | null> => {
  const supabase = await createServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const data = await getCachedGroupData(groupId);
  if (!data) return null;

  const { group, members, mapTheme } = data;

  const currentUserRole =
    user
      ? (members.find((m) => m.user_id === user.id)?.role ?? null)
      : null;

  return {
    group,
    members,
    currentUserRole,
    memberCount: members.length,
    mapTheme,
  };
});

/**
 * Fast unified server action to fetch a complete group bundle (group details + active challenge)
 * in a single request for client-side prefetching and cycling.
 */
export async function getGroupPageBundle(groupId: string): Promise<{
  groupWithMembers: GroupWithMembers | null;
  activeChallenge: import('@/lib/challengeDefaults').GroupChallenge | null;
}> {
  const { getActiveGroupChallenge } = await import('@/app/actions/challengeActions');
  const [groupWithMembers, activeChallenge] = await Promise.all([
    getGroupWithMembers(groupId),
    getActiveGroupChallenge(groupId),
  ]);

  return {
    groupWithMembers,
    activeChallenge,
  };
}

// ---------------------------------------------------------------------------
// Admin Management Actions
// ---------------------------------------------------------------------------

export async function updateGroupName(
  groupId: string,
  newName: string
): Promise<GroupActionResult> {
  const supabase = await createServerClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user || !newName.trim()) {
    return { success: false, error: 'Authentication required and valid name.' };
  }

  const service = createServiceClient();
  const { data: membership } = await service
    .schema('cozy')
    .from('group_members')
    .select('role')
    .eq('group_id', groupId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (membership?.role !== 'admin') {
    return { success: false, error: 'Only admins can update group options.' };
  }

  const { error } = await service
    .schema('cozy')
    .from('groups')
    .update({ name: newName.trim() })
    .eq('id', groupId);

  if (error) {
    return { success: false, error: 'Failed to update group name.' };
  }

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  return { success: true, groupId };
}

export async function removeGroupMember(
  groupId: string,
  targetUserId: string
): Promise<GroupActionResult> {
  const supabase = await createServerClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  const service = createServiceClient();
  const { data: membership } = await service
    .schema('cozy')
    .from('group_members')
    .select('role')
    .eq('group_id', groupId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (membership?.role !== 'admin') {
    return { success: false, error: 'Only admins can remove members.' };
  }

  const { error } = await service
    .schema('cozy')
    .from('group_members')
    .delete()
    .eq('group_id', groupId)
    .eq('user_id', targetUserId);

  if (error) {
    return { success: false, error: 'Failed to remove member.' };
  }

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  return { success: true, groupId };
}

export async function updateMemberRole(
  groupId: string,
  targetUserId: string,
  newRole: 'admin' | 'member'
): Promise<GroupActionResult> {
  const supabase = await createServerClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  const service = createServiceClient();
  const { data: membership } = await service
    .schema('cozy')
    .from('group_members')
    .select('role')
    .eq('group_id', groupId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (membership?.role !== 'admin') {
    return { success: false, error: 'Only admins can update roles.' };
  }

  const { error } = await service
    .schema('cozy')
    .from('group_members')
    .update({ role: newRole })
    .eq('group_id', groupId)
    .eq('user_id', targetUserId);

  if (error) {
    return { success: false, error: 'Failed to update member role.' };
  }

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  return { success: true, groupId };
}
