'use server';

import { createServerClient, createServiceClient } from '@/lib/supabase';
import { revalidatePath } from 'next/cache';

import { GROUP_TYPE_META } from '@/config/groupDefinitions';
export type { GroupTypeMeta } from '@/config/groupDefinitions';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GroupRow {
  id: string;
  name: string;
  type: string;
  min_members: number;
  max_members: number;
  pooled_points: number;
  theme_id: string;
  invite_code: string;
  created_at: string;
}

export interface GroupMemberRow {
  user_id: string;
  role: 'admin' | 'member';
  joined_at: string;
  display_name: string;
  avatar_url: string | null;
  points: number;
}

export interface GroupWithMembers {
  group: GroupRow;
  members: GroupMemberRow[];
  currentUserRole: 'admin' | 'member' | null;
  memberCount: number;
}

export interface MyGroupEntry {
  group: GroupRow;
  role: 'admin' | 'member';
  memberCount: number;
}

export interface GroupActionResult {
  success: boolean;
  groupId?: string;
  error?: string;
}

// ---------------------------------------------------------------------------
// createGroup
//
// Creates a new group with the given name and type, then inserts the
// authenticated user as 'admin'. The invite_code is generated by the DB.
// ---------------------------------------------------------------------------

export async function createGroup(
  name: string,
  type: string
): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  // Validate type
  if (!GROUP_TYPE_META[type]) {
    return { success: false, error: `Invalid group type: ${type}` };
  }

  const meta = GROUP_TYPE_META[type];

  // Use service client for writes (RLS allows authenticated SELECT only)
  const service = createServiceClient();

  const { data: group, error: insertError } = await service
    .schema('cozy')
    .from('groups')
    .insert({
      name: name.trim(),
      type,
      max_members: meta.capacity,
      theme_id: meta.themeId,
    })
    .select('id')
    .single();

  if (insertError || !group) {
    console.error('[createGroup] Insert error:', insertError?.message);
    return { success: false, error: 'Failed to create group. Please try again.' };
  }

  // Add creator as admin
  const { error: memberError } = await service
    .schema('cozy')
    .from('group_members')
    .insert({ group_id: group.id, user_id: user.id, role: 'admin' });

  if (memberError) {
    console.error('[createGroup] Member insert error:', memberError.message);
    // Rollback the group — best effort
    await service.schema('cozy').from('groups').delete().eq('id', group.id);
    return { success: false, error: 'Failed to add you to the group. Please try again.' };
  }

  revalidatePath('/groups');
  return { success: true, groupId: group.id };
}

// ---------------------------------------------------------------------------
// joinGroup
//
// Validates group existence and capacity, then inserts the user as 'member'.
// Uses ON CONFLICT DO NOTHING so re-joining an existing group is a no-op.
// ---------------------------------------------------------------------------

export async function joinGroup(inviteCode: string): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  // Resolve group by invite code (public lookup — service bypasses RLS)
  const service = createServiceClient();

  const { data: group, error: fetchError } = await service
    .schema('cozy')
    .from('groups')
    .select('id, max_members')
    .eq('invite_code', inviteCode.trim().toLowerCase())
    .maybeSingle();

  if (fetchError) {
    console.error('[joinGroup] Fetch error:', fetchError.message);
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if (!group) {
    return { success: false, error: 'Invalid invite code. Double-check and try again.' };
  }

  // Check current member count against capacity
  const { count, error: countError } = await service
    .schema('cozy')
    .from('group_members')
    .select('*', { count: 'exact', head: true })
    .eq('group_id', group.id);

  if (countError) {
    console.error('[joinGroup] Count error:', countError.message);
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if ((count ?? 0) >= group.max_members) {
    return { success: false, error: 'This group is at full capacity. Ask the admin to upgrade the tier.' };
  }

  const { error: insertError } = await service
    .schema('cozy')
    .from('group_members')
    .upsert(
      { group_id: group.id, user_id: user.id, role: 'member' },
      { onConflict: 'group_id,user_id', ignoreDuplicates: true }
    );

  if (insertError) {
    console.error('[joinGroup] Insert error:', insertError.message);
    return { success: false, error: 'Failed to join group. Please try again.' };
  }

  revalidatePath('/groups');
  revalidatePath(`/groups/${group.id}`);
  return { success: true, groupId: group.id };
}

// ---------------------------------------------------------------------------
// upgradeGroupTier
//
// Validates that the caller is an admin and that the current member count
// meets requiredMinMembers before upgrading the group type and theme_id.
// ---------------------------------------------------------------------------

export async function upgradeGroupTier(
  groupId: string,
  newType: string,
  requiredMinMembers: number
): Promise<GroupActionResult> {
  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  if (!GROUP_TYPE_META[newType]) {
    return { success: false, error: `Invalid group type: ${newType}` };
  }

  const service = createServiceClient();

  // Verify caller is admin
  const { data: membership, error: memberError } = await service
    .schema('cozy')
    .from('group_members')
    .select('role')
    .eq('group_id', groupId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (memberError || !membership || membership.role !== 'admin') {
    return { success: false, error: 'Only group admins can upgrade the tier.' };
  }

  // Check current member count
  const { count, error: countError } = await service
    .schema('cozy')
    .from('group_members')
    .select('*', { count: 'exact', head: true })
    .eq('group_id', groupId);

  if (countError) {
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  if ((count ?? 0) < requiredMinMembers) {
    return {
      success: false,
      error: `You need at least ${requiredMinMembers} members to upgrade to ${GROUP_TYPE_META[newType].label}.`,
    };
  }

  const meta = GROUP_TYPE_META[newType];

  const { error: updateError } = await service
    .schema('cozy')
    .from('groups')
    .update({ type: newType, theme_id: meta.themeId, max_members: meta.capacity })
    .eq('id', groupId);

  if (updateError) {
    console.error('[upgradeGroupTier] Update error:', updateError.message);
    return { success: false, error: 'Failed to upgrade group. Please try again.' };
  }

  revalidatePath(`/groups/${groupId}`);
  revalidatePath('/groups');
  return { success: true, groupId };
}

// ---------------------------------------------------------------------------
// contributeToGroup
//
// Transfers `points` from the authenticated user's personal balance into the
// group's pooled_points bank.
//
// Calls cozy.contribute_points(p_user_id, p_group_id, p_points) RPC which
// atomically:
//   - Verifies the user is a group member
//   - Verifies the user has >= points
//   - Deducts points from cozy.users.points
//   - Credits points to cozy.groups.pooled_points
//   - Returns (new_personal_points INT, new_pooled_points INT)
// ---------------------------------------------------------------------------

export interface ContributeResult {
  success: boolean;
  newPersonalPoints?: number;
  newPooledPoints?: number;
  error?: string;
}

export async function contributeToGroup(
  groupId: string,
  points: number
): Promise<ContributeResult> {
  if (points < 1 || !Number.isInteger(points)) {
    return { success: false, error: 'Contribution must be a positive whole number.' };
  }

  const supabase = await createServerClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Authentication required.' };
  }

  const { data, error } = await supabase.schema('cozy').rpc('contribute_points', {
    p_user_id: user.id,
    p_group_id: groupId,
    p_points: points,
  });

  if (error) {
    if (error.message.includes('Insufficient points') || error.message.includes('insufficient')) {
      return { success: false, error: "You don't have enough points for that contribution." };
    }
    if (error.message.includes('not a member') || error.message.includes('membership')) {
      return { success: false, error: 'You must be a group member to contribute.' };
    }
    console.error('[contributeToGroup] RPC error:', error.message);
    return { success: false, error: 'Something went wrong. Please try again.' };
  }

  const result = (Array.isArray(data) ? data[0] : data) as {
    new_personal_points: number;
    new_pooled_points: number;
  };

  revalidatePath(`/groups/${groupId}`);

  return {
    success: true,
    newPersonalPoints: result.new_personal_points,
    newPooledPoints: result.new_pooled_points,
  };
}

// ---------------------------------------------------------------------------
// getMyGroups  (server helper — not a mutation action)
//
// Returns all groups the authenticated user belongs to, with member counts.
// Called by the Groups Hub server component.
// ---------------------------------------------------------------------------

export async function getMyGroups(): Promise<MyGroupEntry[]> {
  const supabase = await createServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return [];

  // Fetch memberships + group rows (RLS ensures only own groups are visible)
  const { data, error } = await supabase
    .schema('cozy')
    .from('group_members')
    .select(`
      role,
      group:group_id (
        id, name, type, min_members, max_members, pooled_points, theme_id, invite_code, created_at
      )
    `)
    .eq('user_id', user.id);

  if (error) {
    console.error('[getMyGroups] Query error:', error.message);
    return [];
  }

  if (!data || data.length === 0) return [];

  // Supabase infers nested FK joins as arrays — cast through unknown to the
  // actual runtime shape (many-to-one join returns a plain object, not array).
  type RawMembership = { role: 'admin' | 'member'; group: GroupRow };
  const rows = data as unknown as RawMembership[];

  // Fetch member counts for each group (service client — no per-user RLS)
  const service = createServiceClient();
  const groupIds = rows.map((row) => row.group.id);

  const { data: memberCounts } = await service
    .schema('cozy')
    .from('group_members')
    .select('group_id')
    .in('group_id', groupIds);

  const countMap: Record<string, number> = {};
  (memberCounts ?? []).forEach((row: { group_id: string }) => {
    countMap[row.group_id] = (countMap[row.group_id] ?? 0) + 1;
  });

  return rows.map((row) => ({
    group: row.group,
    role: row.role,
    memberCount: countMap[row.group.id] ?? 0,
  }));
}

// ---------------------------------------------------------------------------
// getGroupWithMembers  (server helper — not a mutation action)
//
// Returns the group row + all member profiles for the dynamic group view page.
// Called by app/groups/[id]/page.tsx.
// ---------------------------------------------------------------------------

export async function getGroupWithMembers(
  groupId: string
): Promise<GroupWithMembers | null> {
  const supabase = await createServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const service = createServiceClient();

  // Fetch group (service client to bypass per-member RLS, still safe — display only)
  const { data: group, error: groupError } = await service
    .schema('cozy')
    .from('groups')
    .select('id, name, type, min_members, max_members, pooled_points, theme_id, invite_code, created_at')
    .eq('id', groupId)
    .single();

  if (groupError || !group) {
    return null;
  }

  // Fetch members joined with user profiles
  const { data: memberships, error: memberError } = await service
    .schema('cozy')
    .from('group_members')
    .select(`
      user_id,
      role,
      joined_at,
      user:user_id (
        display_name,
        avatar_url,
        points
      )
    `)
    .eq('group_id', groupId);

  if (memberError) {
    console.error('[getGroupWithMembers] Member query error:', memberError.message);
    return null;
  }

  // Supabase infers nested FK joins as arrays — cast to the actual runtime shape.
  type RawMemberRow = {
    user_id: string;
    role: 'admin' | 'member';
    joined_at: string;
    user: { display_name: string; avatar_url: string | null; points: number };
  };
  const rawMembers = (memberships ?? []) as unknown as RawMemberRow[];

  const members: GroupMemberRow[] = rawMembers.map((row) => ({
    user_id: row.user_id,
    role: row.role,
    joined_at: row.joined_at,
    display_name: row.user.display_name,
    avatar_url: row.user.avatar_url,
    points: row.user.points ?? 0,
  }));

  const currentUserRole =
    user
      ? (members.find((m) => m.user_id === user.id)?.role ?? null)
      : null;

  return {
    group: group as GroupRow,
    members,
    currentUserRole,
    memberCount: members.length,
  };
}
